# Do NOT update manually; changes here will be overwritten by Copier
_commit: a7bd24b
_src_path: https://github.com/grap/oca-addons-repo-template-new.git
ci: GitHub
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: true
github_enable_makepot: false
github_enable_stale_action: false
github_enforce_dev_status_compatibility: false
include_wkhtmltopdf: false
odoo_real_version: 12.0
odoo_test_flavor: Odoo
odoo_version: 16.0
org_name: GRAP
org_slug: grap
rebel_module_groups: []
repo_description: This repository contains Odoo modules developped by the company
    GRAP before they are shared to the Odoo Community Association.
repo_name: Incubator of Odoo (formely OpenERP) modules before they are shared to the
    OCA
repo_slug: grap-odoo-incubator
repo_website: https://github.com/grap/grap-odoo-incubator

