# Copyright (C) 2025 - Today: GRAP (http://www.grap.coop)
# @author Julien WESTE
# @author: Sylvain LE GAL (https://twitter.com/legalsylvain)
# @author: Quentin DUPONT (quentin.dupont@grap.coop)
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl.html).

from odoo import Command, _, api, fields, models
from odoo.exceptions import UserError


class StockPicking(models.Model):
    _inherit = "stock.picking"

    _ACCOUNT_MOVE_STATE = [
        ("no_need", "No need"),
        ("waiting", "Waiting"),
        ("to_do", "To Do"),
        ("done", "Generated"),
    ]

    # Columns section
    account_move_id = fields.Many2one(
        comodel_name="account.move", string="Account Move", readonly=True, copy=False
    )

    account_move_state = fields.Selection(
        selection=_ACCOUNT_MOVE_STATE,
        string="Account Move Status",
        compute="_compute_account_move_state",
        store=True,
    )

    # Compute Section
    @api.depends(
        "state",
        "account_move_id",
        "picking_type_id",
        "picking_type_id.journal_id",
        "picking_type_id.account_id",
    )
    def _compute_account_move_state(self):
        for picking in self:
            if len(picking.picking_type_id.journal_id) != 0:
                if picking.state == "cancel":
                    picking.account_move_state = "no_need"
                elif picking.state == "done":
                    picking.account_move_state = (
                        "done" if picking.account_move_id else "to_do"
                    )
                else:
                    picking.account_move_state = "waiting"

            else:
                picking.account_move_state = "no_need"

    def generate_account_move(self):
        """Set the stock pickings to 'done' and create account moves"""
        if self.filtered(lambda x: x.state != "done"):
            raise UserError(
                _("Unable to generate account move for not done stock pickings.")
            )
        AccountMove = self.env["account.move"].with_context(
            skip_account_move_synchronization=True, skip_invoice_sync=True
        )

        picking_data = {}

        # Group pickings by their accounting entry key
        for picking in self.filtered(lambda x: x.account_move_state == "to_do"):
            picking_key = picking._get_expense_entry_key()
            if picking_key in picking_data:
                picking_data[picking_key] |= picking
            else:
                picking_data[picking_key] = picking

        # Loop through each group of pickings
        for picking_key, pickings in picking_data.items():
            account_move_vals = pickings._prepare_account_move(picking_key)
            move_data = {}

            for move in pickings.mapped("move_ids"):
                move_key = move._get_expense_entry_key()
                if move_key in move_data:
                    move_data[move_key] |= move
                else:
                    move_data[move_key] = move

            for move_key, moves in move_data.items():
                account_move_vals["line_ids"].append(
                    Command.create(
                        moves._prepare_account_move_line_charge(
                            picking_key, move_key, account_move_vals
                        )
                    )
                )

                account_move_vals["line_ids"].append(
                    Command.create(
                        moves._prepare_account_move_line_uncharge(
                            picking_key, move_key, account_move_vals
                        )
                    )
                )
            account_move = AccountMove.create(account_move_vals)
            account_move.action_post()

            # Link pickings to the account move
            pickings.write({"account_move_id": account_move.id})

        return True

    def _get_expense_entry_key(self):
        """
        Define how to group to generare a unique Account Move.
        By default, an entry is generated by Picking_type, by direction
        and by month.
        Overwrite this function to change the behaviour.
        Note that picking_type_id is mandatory.
        """
        self.ensure_one()
        dt = fields.Date.from_string(self.date_done)
        if self.direction_type == "undefined":
            raise UserError(
                _(
                    "Unable to generate an expense entry for the"
                    " picking %(picking_name)s."
                    " Unable to define the direction.",
                    picking_name=self.name,
                )
            )
        return (
            self.picking_type_id,
            self.direction_type,
            "%d-%d" % (dt.year, dt.month),
        )

    def _prepare_account_move(self, stock_picking_entry_key):
        picking_type = stock_picking_entry_key[0]
        return {
            "journal_id": picking_type.journal_id.id,
            "company_id": picking_type.company_id.id,
            "ref": _(
                "Expense Transfert (%(picking_type_name)s)",
                picking_type_name=picking_type.name,
            ),
            "date": max(self.mapped("date_done")),
            "line_ids": [],
        }

    def action_mass_generate_wizard(self):
        return {
            "name": _("Mass generate Account Moves"),
            "type": "ir.actions.act_window",
            "view_mode": "form",
            "res_model": "stock.picking.mass.generate.wizard",
            "views": [
                [
                    self.env.ref(
                        "stock_picking_account_move.view_stock_picking_mass_generate_wizard_form"
                    ).id,
                    "form",
                ]
            ],
            "target": "new",
        }
