import setuptools

with open('VERSION.txt', 'r') as f:
    version = f.read().strip()

setuptools.setup(
    name="odoo8-addons-grap-grap-odoo-incubator",
    description="Meta package for grap-grap-odoo-incubator Odoo addons",
    version=version,
    install_requires=[
        'odoo8-addon-account_fiscal_position_tax_included',
        'odoo8-addon-account_invoice_supplierinfo_update_triple_discount',
        'odoo8-addon-account_product_fiscal_classification_usage_group',
        'odoo8-addon-base_company_legal_info',
        'odoo8-addon-duplication_account_invoice',
        'odoo8-addon-duplication_sale_order',
        'odoo8-addon-l10n_fr_pos_cert_extra',
        'odoo8-addon-mail_send_bcc',
        'odoo8-addon-mass_action',
        'odoo8-addon-mass_linking',
        'odoo8-addon-mass_merging_content',
        'odoo8-addon-mass_merging_content_test',
        'odoo8-addon-mass_operation_abstract',
        'odoo8-addon-mobile_app_purchase',
        'odoo8-addon-multi_search_abstract',
        'odoo8-addon-multi_search_partner',
        'odoo8-addon-multi_search_product',
        'odoo8-addon-pos_change_payment',
        'odoo8-addon-pos_check_session_state',
        'odoo8-addon-pos_confirm_window_close',
        'odoo8-addon-pos_copy_order_opened_session',
        'odoo8-addon-pos_done_order_load',
        'odoo8-addon-pos_environment',
        'odoo8-addon-pos_invoicing',
        'odoo8-addon-pos_journal_image',
        'odoo8-addon-pos_limit_unknown_barcode',
        'odoo8-addon-pos_multicompany',
        'odoo8-addon-pos_multiple_control',
        'odoo8-addon-pos_optional_printing',
        'odoo8-addon-pos_payment_limit',
        'odoo8-addon-pos_payment_usability',
        'odoo8-addon-pos_picking_load_partner_name',
        'odoo8-addon-pos_product_without_image',
        'odoo8-addon-pos_sector',
        'odoo8-addon-pos_street_market',
        'odoo8-addon-product_categ_search_complete_name',
        'odoo8-addon-product_category_product_qty',
        'odoo8-addon-product_category_usage_group',
        'odoo8-addon-product_ean13_image',
        'odoo8-addon-product_ean_duplicates',
        'odoo8-addon-product_print_category',
        'odoo8-addon-product_sale_tax_price_included',
        'odoo8-addon-product_simple_pricelist',
        'odoo8-addon-product_supplierinfo_quick_edit',
        'odoo8-addon-product_supplierinfo_triple_discount',
        'odoo8-addon-product_uom_use_type',
        'odoo8-addon-res_company_active',
        'odoo8-addon-res_company_category',
        'odoo8-addon-sale_line_change_custom',
        'odoo8-addon-simple_tax_account',
        'odoo8-addon-simple_tax_purchase',
        'odoo8-addon-simple_tax_sale',
        'odoo8-addon-stock_easy_valuation',
        'odoo8-addon-stock_internal_use_of_products',
        'odoo8-addon-stock_inventory_merge',
        'odoo8-addon-stock_inventory_valuation',
        'odoo8-addon-stock_inventory_valuation_merge',
        'odoo8-addon-web_base_url_force',
    ],
    classifiers=[
        'Programming Language :: Python',
        'Framework :: Odoo',
    ]
)
